### ISSUE TITLE
Have a screenshot you can drop into your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [putkoff/Python-Tools#1]
❤ that your application has a GUI.  In the Python world, that's uncommon.  It's also visual by definition.  I'm sure visitors to your repo would enjoy seeing what you created.

**Comment by putkoff** [comment]
started using simplegui in ~early 2022. I love what yall have done. I started converting all of my old projects to sinplegui mid 2022 and now, I dont make anything without it. I'm always checking chatgpt on the choice when I build with them. Yall have done a great service to python. Big thanks!

    On Saturday, July 22, 2023 at 10:02:41 AM CDT, PySimpleGUI ***@***.***> wrote:  
 
 


 ❤ that your application has a GUI. In the Python world, that's uncommon. It's also visual by definition. I'm sure visitors to your repo would enjoy seeing what you created.

**Comment by PySimpleGUI** [comment]
Ooooo!  Nice screenshot ![image](https://github.com/putkoff/Python-Tools/assets/46163555/8623cb82-85e7-4f35-96e2-a7fc541e7a56)!  Thank you for posting one and thank you for the kind words.  They've fueled the project.
